org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRResources=true
kotlin.code.style=official
# Use copied JDK without spaces to avoid MSYS path bug
org.gradle.java.home=C:/tmpjbr_test/jbr
android.suppressUnsupportedCompileSdk=36
